### ISSUE TITLE
Does not work at all with angular 10

### ISSUE THREAD

**Issue by smlombardi** [kreuzerk/ng-sortgrid#46]
See Stackblitz example: https://angular-ivy-ziayzb.stackblitz.io

No grid appears, although inspecting the output shows repeated divs with directives are applied.

Click and item throws a console error.

**Comment by kreuzerk** [comment]
Thx a lot for the reproduction - There are no styles applied by default. This means the sort grid is generic. Its up to you to apply the styles for the grid and the elements. The styles you see in the demo are custom styles.

Its implemented like this because the purpose of the sortgrid is to be as generic as possible. So the sortgrid doesn't style elements.

Whats confusing me though is that the items are not draggable in your example. Will try to reproduce this.

**Comment by smlombardi** [comment]
yes, if they were draggable but unstyled I would have tried to fix the layout.  but nothing drags or drops/

**Comment by kreuzerk** [comment]
yes - I will have a look at this as soon as I find time
