### ISSUE TITLE
ng-sortgrid doesn't work in lazy loaded modules

### ISSUE THREAD

**Issue by nikhil-jain655** [kreuzerk/ng-sortgrid#58]
Hi Kevin,

Thanks a lot for creating ng-sortgrid !

ng-sortgrid works perfectly fine in app.component.html or when used in a component without lazy loading. 

While Using ng-sortgrid in lazy loaded module. I am getting the following error-

Can't bind to 'item' since it isn't a known property of 'ngsg-card'.
1. If 'ngsg-card' is an Angular component and it has 'item' input, then verify that it is part of this module.
2. If 'ngsg-card' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component.

is it possible to use ng-sortgrid in lazy loaded modules?

"@angular/cli": "~8.3.17"
"ng-sortgrid": "1.3.3"

Best Regards
Nik

**Comment by kreuzerk** [comment]
Hi, @nikhil-jain655 thanks for reporting this issue. I think this problem comes when trying to use ng-sortgrid in an Angular < 10 SPA. Unfortunately, Angular libs always have to be the same version or lower than the SPA. I would recommend you to upgrade your Angular app to the latest version or try to use sortgrid 1.x.

**Comment by nikhil-jain655** [comment]
Hi Kevin,

Thanks for the response.

ngSortGrid seems to work in lazy loaded modules after adding 'CUSTOM_ELEMENTS_SCHEMA' to the Schemas array in lazy loaded module.

imports: [],
schemas: [CUSTOM_ELEMENTS_SCHEMA],

Best Regards,
Nik
